name: flutter_core
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #fire_base:
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  #localstore:
  shared_preferences: ^2.0.15

  #responsive
  flutter_screenutil: ^5.5.3+2

  #image
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.0

  #status internet
  connectivity_plus: ^3.0.3

  #extension
  copy_with_extension: ^4.0.2
  logger: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  freezed_annotation: ^2.0.3

  #preview devicce
  device_preview: ^1.1.0

  #localozaion language
  easy_localization: any

  #bloc
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2

  #notifications
  flutter_local_notifications: ^13.0.0

  #splash & icon app
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15

  #network
  dio: ^4.0.6
  retrofit: ^3.3.1
  json_annotation: ^4.5.0



  #cache network
  dio_http_cache_lts: ^0.4.1

  #route
  auto_route: ^5.0.2

  #widget
  shimmer: ^2.0.0

  #env
  flutter_dotenv: ^5.0.2

  # 3th lib
  top_snackbar_flutter: ^2.1.1
  dartz: ^0.10.1
  infinite_scroll_pagination: ^3.2.0
  photo_view: ^0.14.0
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  firebase_remote_config: ^3.0.13
  firebase_analytics: ^10.1.4
  dio_cache_interceptor: ^3.4.0
  side_navigation: ^1.0.4
  adaptive_scrollbar: ^2.1.2
  page_transition: ^2.1.0
  zoom_widget: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.2
  copy_with_extension_gen: ^4.0.2
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  json_serializable: ^6.2.0
  retrofit_generator: ^4.2.0
  freezed: ^2.0.3+1
  flutter_lints: ^2.0.0
  injectable_generator: any
  # flutter_dotenv: ^5.0.2

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/svg/
    - assets/fonts/
    - assets/icon/
    - assets/env/
    - assets/json/
  fonts:
    - family: SVNGilroy
      fonts:
        - asset: assets/fonts/SVNGilroy-Light.otf
          weight: 300
        - asset: assets/fonts/SVNGilroy-Bold.otf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: null