// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx0ZS0cWsxgSL-HEPytDqRIAbEQM9o7sE',
    appId: '1:525689268476:web:4cc8940dd415bcf9088f79',
    messagingSenderId: '525689268476',
    projectId: 'flutter-core-tecinus',
    authDomain: 'flutter-core-tecinus.firebaseapp.com',
    storageBucket: 'flutter-core-tecinus.appspot.com',
    measurementId: 'G-2E9YJ6YFQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAstfiNZ6DHsAqB7N7YQS70xgpIjuRG_W4',
    appId: '1:525689268476:android:e4808cc8e58ff106088f79',
    messagingSenderId: '525689268476',
    projectId: 'flutter-core-tecinus',
    storageBucket: 'flutter-core-tecinus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyf0VrXhcV4lcXyO45G-ljUESOkL-lfZ8',
    appId: '1:525689268476:ios:ae84b1f15e23bbee088f79',
    messagingSenderId: '525689268476',
    projectId: 'flutter-core-tecinus',
    storageBucket: 'flutter-core-tecinus.appspot.com',
    iosClientId: '525689268476-hr2730inl27esu80m8ji4515r2evgn8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyf0VrXhcV4lcXyO45G-ljUESOkL-lfZ8',
    appId: '1:525689268476:ios:ae84b1f15e23bbee088f79',
    messagingSenderId: '525689268476',
    projectId: 'flutter-core-tecinus',
    storageBucket: 'flutter-core-tecinus.appspot.com',
    iosClientId: '525689268476-hr2730inl27esu80m8ji4515r2evgn8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCore',
  );
}
